import { type INodeProperties } from "n8n-workflow";

const show = (operation: string) => ({
  show: { resource: ["channel"], operation: [operation] },
});

export const channelDescription: INodeProperties[] = [
  {
    displayName: "Operation",
    name: "operation",
    type: "options",
    noDataExpression: true,
    displayOptions: { show: { resource: ["channel"] } },
    options: [
      {
        name: "Analytics",
        value: "analytics",
        action: "Get channel analytics",
        description: "Retrieve time-series analytics metrics for a channel",
      },
      {
        name: "Find Breakout",
        value: "findBreakout",
        action: "Find breakout channels",
        description: "Discover rapidly growing breakout channels for a query",
      },
      {
        name: "Find Similar",
        value: "findSimilar",
        action: "Find similar channels",
        description: "Discover channels similar to a given niche",
      },
      {
        name: "Get Many by IDs",
        value: "getMany",
        action: "Get many channels by i ds",
        description: "Fetch multiple channels by their YouTube IDs",
      },
      {
        name: "Get My Channels",
        value: "getMyChannels",
        action: "Get my channels",
        description: "List the channels owned by the authenticated user",
      },
      {
        name: "Get Performance Trends",
        value: "getPerformanceTrends",
        action: "Get channel performance trends",
        description: "Retrieve performance trend data for a channel",
      },
      {
        name: "Get Stats",
        value: "getStats",
        action: "Get channel stats",
        description: "Retrieve summary statistics for a channel",
      },
      {
        name: "Get Videos",
        value: "getVideos",
        action: "Get channel videos",
        description: "List videos published by a channel",
      },
      {
        name: "List Competitors",
        value: "listCompetitors",
        action: "List channel competitors",
        description: "List the tracked competitors for a channel",
      },
      {
        name: "Search",
        value: "search",
        action: "Search channels",
        description: "Search channels with rich filters",
      },
      {
        name: "Update Competitors",
        value: "updateCompetitors",
        action: "Update channel competitors",
        description: "Follow or unfollow competitors for a channel",
      },
    ],
    default: "analytics",
  },

  // ----- Analytics -----
  {
    displayName: "Channel ID",
    name: "channelId",
    required: true,
    type: "string",
    default: "",
    description: "YouTube channel ID to retrieve analytics for",
    displayOptions: show("analytics"),
  },
  {
    displayName: "Start Date",
    name: "startDate",
    type: "string",
    default: "",
    description: "Start of the analytics date range (e.g. YYYY-MM-DD)",
    displayOptions: show("analytics"),
  },
  {
    displayName: "End Date",
    name: "endDate",
    type: "string",
    default: "",
    description: "End of the analytics date range (e.g. YYYY-MM-DD)",
    displayOptions: show("analytics"),
  },
  {
    displayName: "Metrics",
    name: "metrics",
    type: "string",
    default: "",
    placeholder: "views, likes, comments",
    description: "Analytics metrics to return (comma-separated)",
    displayOptions: show("analytics"),
  },
  {
    displayName: "Dimensions",
    name: "dimensions",
    type: "string",
    default: "",
    placeholder: "day, country",
    description: "Analytics dimensions to group by (comma-separated)",
    displayOptions: show("analytics"),
  },
  {
    displayName: "Max Results",
    name: "maxResults",
    type: "number",
    default: 0,
    description: "Maximum number of analytics rows to return",
    displayOptions: show("analytics"),
  },
  {
    displayName: "Filters",
    name: "filters",
    type: "string",
    default: "",
    description: "Analytics filter expression to apply",
    displayOptions: show("analytics"),
  },
  {
    displayName: "Sort",
    name: "sort",
    type: "string",
    default: "",
    description: "Sort field, prefix with '-' for descending (e.g. '-views')",
    displayOptions: show("analytics"),
  },

  // ----- Find Breakout -----
  {
    displayName: "Query",
    name: "query",
    required: true,
    type: "string",
    default: "",
    description: "Search query to find breakout channels for",
    displayOptions: show("findBreakout"),
  },
  {
    displayName: "Channel Type",
    name: "channelType",
    type: "options",
    options: [
      { name: "Long", value: "long" },
      { name: "Mixed", value: "mixed" },
      { name: "Short", value: "short" },
    ],
    default: "long",
    description: "Type of channel content to filter by",
    displayOptions: show("findBreakout"),
  },
  {
    displayName: "Country",
    name: "country",
    type: "string",
    default: "",
    placeholder: "US",
    description: "ISO 3166-1 alpha-2 country code to filter by",
    displayOptions: show("findBreakout"),
  },
  {
    displayName: "Subscriber Count Min",
    name: "subscriberCountMin",
    type: "number",
    default: 0,
    description: "Minimum subscriber count to include",
    displayOptions: show("findBreakout"),
  },
  {
    displayName: "Subscriber Count Max",
    name: "subscriberCountMax",
    type: "number",
    default: 0,
    description: "Maximum subscriber count to include",
    displayOptions: show("findBreakout"),
  },
  {
    displayName: "Faceless",
    name: "faceless",
    type: "boolean",
    default: false,
    description: "Whether to only include faceless channels",
    displayOptions: show("findBreakout"),
  },
  {
    displayName: "Limit",
    name: "limit",
    type: "number",
    typeOptions: { minValue: 1 },
    default: 50,
    description: "Max number of results to return",
    displayOptions: show("findBreakout"),
  },

  // ----- Find Similar -----
  {
    displayName: "Niche",
    name: "niche",
    required: true,
    type: "string",
    default: "",
    description: "Niche or topic to find similar channels for",
    displayOptions: show("findSimilar"),
  },
  {
    displayName: "Min Subscribers",
    name: "minSubscribers",
    type: "number",
    default: 0,
    description: "Minimum subscriber count to include",
    displayOptions: show("findSimilar"),
  },
  {
    displayName: "Max Subscribers",
    name: "maxSubscribers",
    type: "number",
    default: 0,
    description: "Maximum subscriber count to include",
    displayOptions: show("findSimilar"),
  },
  {
    displayName: "Country",
    name: "country",
    type: "string",
    default: "",
    placeholder: "US",
    description: "ISO 3166-1 alpha-2 country code to filter by",
    displayOptions: show("findSimilar"),
  },
  {
    displayName: "Language",
    name: "language",
    type: "string",
    default: "",
    placeholder: "en",
    description: "ISO 639-1 language code to filter by",
    displayOptions: show("findSimilar"),
  },
  {
    displayName: "Size",
    name: "size",
    type: "number",
    default: 0,
    description: "Number of similar channels to return",
    displayOptions: show("findSimilar"),
  },
  {
    displayName: "Exclude Channel IDs",
    name: "excludeChannelIds",
    type: "string",
    default: "",
    placeholder: "a, b, c",
    description: "Channel IDs to exclude from the results (comma-separated)",
    displayOptions: show("findSimilar"),
  },

  // ----- Get Many by IDs -----
  {
    displayName: "Channel IDs",
    name: "channelIds",
    required: true,
    type: "string",
    default: "",
    placeholder: "a, b, c",
    description: "YouTube channel IDs to fetch (comma-separated)",
    displayOptions: show("getMany"),
  },

  // ----- Get Performance Trends -----
  {
    displayName: "Channel ID",
    name: "channelId",
    required: true,
    type: "string",
    default: "",
    description: "YouTube channel ID to retrieve performance trends for",
    displayOptions: show("getPerformanceTrends"),
  },

  // ----- Get Stats -----
  {
    displayName: "Channel ID",
    name: "channelId",
    required: true,
    type: "string",
    default: "",
    description: "YouTube channel ID to retrieve stats for",
    displayOptions: show("getStats"),
  },
  {
    displayName: "From",
    name: "from",
    type: "string",
    default: "",
    description: "Start of the stats date range (e.g. YYYY-MM-DD)",
    displayOptions: show("getStats"),
  },
  {
    displayName: "To",
    name: "to",
    type: "string",
    default: "",
    description: "End of the stats date range (e.g. YYYY-MM-DD)",
    displayOptions: show("getStats"),
  },

  // ----- Get Videos -----
  {
    displayName: "Channel ID",
    name: "channelId",
    required: true,
    type: "string",
    default: "",
    description: "YouTube channel ID to list videos for",
    displayOptions: show("getVideos"),
  },
  {
    displayName: "Video Format",
    name: "videoFormat",
    required: true,
    type: "options",
    options: [
      { name: "Live", value: "live" },
      { name: "Long", value: "long" },
      { name: "Short", value: "short" },
    ],
    default: "long",
    description: "Video format to filter by",
    displayOptions: show("getVideos"),
  },
  {
    displayName: "Popular",
    name: "popular",
    type: "boolean",
    default: false,
    description: "Whether to return only popular videos",
    displayOptions: show("getVideos"),
  },

  // ----- List Competitors -----
  {
    displayName: "YouTube Channel ID",
    name: "youtubeChannelId",
    required: true,
    type: "string",
    default: "",
    description: "YouTube channel ID to list competitors for",
    displayOptions: show("listCompetitors"),
  },

  // ----- Search -----
  {
    displayName: "Query",
    name: "query",
    type: "string",
    default: "",
    description: "Free-text query to search channels by",
    displayOptions: show("search"),
  },
  {
    displayName: "Channel Type",
    name: "channelType",
    type: "options",
    options: [
      { name: "Long", value: "long" },
      { name: "Mixed", value: "mixed" },
      { name: "Short", value: "short" },
    ],
    default: "long",
    description: "Type of channel content to filter by",
    displayOptions: show("search"),
  },
  {
    displayName: "Country",
    name: "country",
    type: "string",
    default: "",
    placeholder: "a, b, c",
    description:
      "ISO 3166-1 alpha-2 country codes to filter by (comma-separated)",
    displayOptions: show("search"),
  },
  {
    displayName: "Languages",
    name: "languages",
    type: "string",
    default: "",
    placeholder: "a, b, c",
    description: "ISO 639-1 language codes to filter by (comma-separated)",
    displayOptions: show("search"),
  },
  {
    displayName: "Subscriber Count Min",
    name: "subscriberCountMin",
    type: "number",
    default: 0,
    description: "Minimum subscriber count to include",
    displayOptions: show("search"),
  },
  {
    displayName: "Subscriber Count Max",
    name: "subscriberCountMax",
    type: "number",
    default: 0,
    description: "Maximum subscriber count to include",
    displayOptions: show("search"),
  },
  {
    displayName: "View Count Min",
    name: "viewCountMin",
    type: "number",
    default: 0,
    description: "Minimum total view count to include",
    displayOptions: show("search"),
  },
  {
    displayName: "View Count Max",
    name: "viewCountMax",
    type: "number",
    default: 0,
    description: "Maximum total view count to include",
    displayOptions: show("search"),
  },
  {
    displayName: "Video Count Min",
    name: "videoCountMin",
    type: "number",
    default: 0,
    description: "Minimum video count to include",
    displayOptions: show("search"),
  },
  {
    displayName: "Video Count Max",
    name: "videoCountMax",
    type: "number",
    default: 0,
    description: "Maximum video count to include",
    displayOptions: show("search"),
  },
  {
    displayName: "Faceless",
    name: "faceless",
    type: "boolean",
    default: false,
    description: "Whether to only include faceless channels",
    displayOptions: show("search"),
  },
  {
    displayName: "Breakout Channel",
    name: "breakoutChannel",
    type: "boolean",
    default: false,
    description: "Whether to only include breakout channels",
    displayOptions: show("search"),
  },
  {
    displayName: "Sort",
    name: "sort",
    type: "options",
    options: [
      { name: "Last Video Published", value: "lastVideoPublished" },
      { name: "Relevance", value: "relevance" },
      { name: "Subs Growth 30d", value: "subsGrowth30d" },
      { name: "Subscriber Count", value: "subscriberCount" },
      { name: "Views Growth 30d", value: "viewsGrowth30d" },
    ],
    default: "relevance",
    description: "Field to sort the search results by",
    displayOptions: show("search"),
  },
  {
    displayName: "Limit",
    name: "limit",
    type: "number",
    typeOptions: { minValue: 1 },
    default: 50,
    description: "Max number of results to return",
    displayOptions: show("search"),
  },
  {
    displayName: "Additional Filters",
    name: "additionalFilters",
    type: "collection",
    default: {},
    placeholder: "Add Filter",
    description: "Additional long-tail filters for channel search",
    displayOptions: show("search"),
    options: [
      {
        displayName: "Channel Title",
        name: "channelTitle",
        type: "string",
        default: "",
        description: "Channel title to match against",
      },
      {
        displayName: "Channel Title Match",
        name: "channelTitleMatch",
        type: "options",
        options: [
          { name: "Exact", value: "exact" },
          { name: "Fuzzy", value: "fuzzy" },
        ],
        default: "exact",
        description: "How to match the channel title",
      },
      {
        displayName: "Description",
        name: "description",
        type: "string",
        default: "",
        description: "Channel description text to match against",
      },
      {
        displayName: "Exact Language",
        name: "exactLanguage",
        type: "boolean",
        default: false,
        description: "Whether to require an exact language match",
      },
      {
        displayName: "Handle",
        name: "handle",
        type: "string",
        default: "",
        description: "Channel handle to match against",
      },
      {
        displayName: "Handle Match",
        name: "handleMatch",
        type: "options",
        options: [
          { name: "Exact", value: "exact" },
          { name: "Fuzzy", value: "fuzzy" },
        ],
        default: "exact",
        description: "How to match the channel handle",
      },
      {
        displayName: "Last Video Published After",
        name: "lastVideoPublishedAfter",
        type: "string",
        default: "",
        description:
          "Only include channels whose last video was published after this date",
      },
      {
        displayName: "Last Video Published Before",
        name: "lastVideoPublishedBefore",
        type: "string",
        default: "",
        description:
          "Only include channels whose last video was published before this date",
      },
      {
        displayName: "Long Avg Duration 1y Max",
        name: "longAvgDuration1yMax",
        type: "number",
        default: 0,
        description:
          "Maximum 1-year average duration of long videos to include",
      },
      {
        displayName: "Long Avg Duration 1y Min",
        name: "longAvgDuration1yMin",
        type: "number",
        default: 0,
        description:
          "Minimum 1-year average duration of long videos to include",
      },
      {
        displayName: "Long Avg Duration 30d Max",
        name: "longAvgDuration30dMax",
        type: "number",
        default: 0,
        description:
          "Maximum 30-day average duration of long videos to include",
      },
      {
        displayName: "Long Avg Duration 30d Min",
        name: "longAvgDuration30dMin",
        type: "number",
        default: 0,
        description:
          "Minimum 30-day average duration of long videos to include",
      },
      {
        displayName: "Long Avg Duration 7d Max",
        name: "longAvgDuration7dMax",
        type: "number",
        default: 0,
        description: "Maximum 7-day average duration of long videos to include",
      },
      {
        displayName: "Long Avg Duration 7d Min",
        name: "longAvgDuration7dMin",
        type: "number",
        default: 0,
        description: "Minimum 7-day average duration of long videos to include",
      },
      {
        displayName: "Long Video Count 1y Max",
        name: "longVideoCount1yMax",
        type: "number",
        default: 0,
        description: "Maximum number of long videos in the last year",
      },
      {
        displayName: "Long Video Count 1y Min",
        name: "longVideoCount1yMin",
        type: "number",
        default: 0,
        description: "Minimum number of long videos in the last year",
      },
      {
        displayName: "Long Video Count 30d Max",
        name: "longVideoCount30dMax",
        type: "number",
        default: 0,
        description: "Maximum number of long videos in the last 30 days",
      },
      {
        displayName: "Long Video Count 30d Min",
        name: "longVideoCount30dMin",
        type: "number",
        default: 0,
        description: "Minimum number of long videos in the last 30 days",
      },
      {
        displayName: "Long Video Count 7d Max",
        name: "longVideoCount7dMax",
        type: "number",
        default: 0,
        description: "Maximum number of long videos in the last 7 days",
      },
      {
        displayName: "Long Video Count 7d Min",
        name: "longVideoCount7dMin",
        type: "number",
        default: 0,
        description: "Minimum number of long videos in the last 7 days",
      },
      {
        displayName: "Long View Count 1y Max",
        name: "longViewCount1yMax",
        type: "number",
        default: 0,
        description: "Maximum long-video view count in the last year",
      },
      {
        displayName: "Long View Count 1y Min",
        name: "longViewCount1yMin",
        type: "number",
        default: 0,
        description: "Minimum long-video view count in the last year",
      },
      {
        displayName: "Long View Count 30d Max",
        name: "longViewCount30dMax",
        type: "number",
        default: 0,
        description: "Maximum long-video view count in the last 30 days",
      },
      {
        displayName: "Long View Count 30d Min",
        name: "longViewCount30dMin",
        type: "number",
        default: 0,
        description: "Minimum long-video view count in the last 30 days",
      },
      {
        displayName: "Long View Count 7d Max",
        name: "longViewCount7dMax",
        type: "number",
        default: 0,
        description: "Maximum long-video view count in the last 7 days",
      },
      {
        displayName: "Long View Count 7d Min",
        name: "longViewCount7dMin",
        type: "number",
        default: 0,
        description: "Minimum long-video view count in the last 7 days",
      },
      {
        displayName: "Main Category",
        name: "mainCategory",
        type: "string",
        default: "",
        placeholder: "a, b, c",
        description: "Main content categories to filter by (comma-separated)",
      },
      {
        displayName: "Niche Confidence Min",
        name: "nicheConfidenceMin",
        type: "number",
        default: 0,
        description: "Minimum niche confidence score to include",
      },
      {
        displayName: "Published After",
        name: "publishedAfter",
        type: "string",
        default: "",
        description: "Only include channels created after this date",
      },
      {
        displayName: "Published Before",
        name: "publishedBefore",
        type: "string",
        default: "",
        description: "Only include channels created before this date",
      },
      {
        displayName: "Short Avg Duration 1y Max",
        name: "shortAvgDuration1yMax",
        type: "number",
        default: 0,
        description:
          "Maximum 1-year average duration of short videos to include",
      },
      {
        displayName: "Short Avg Duration 1y Min",
        name: "shortAvgDuration1yMin",
        type: "number",
        default: 0,
        description:
          "Minimum 1-year average duration of short videos to include",
      },
      {
        displayName: "Short Avg Duration 30d Max",
        name: "shortAvgDuration30dMax",
        type: "number",
        default: 0,
        description:
          "Maximum 30-day average duration of short videos to include",
      },
      {
        displayName: "Short Avg Duration 30d Min",
        name: "shortAvgDuration30dMin",
        type: "number",
        default: 0,
        description:
          "Minimum 30-day average duration of short videos to include",
      },
      {
        displayName: "Short Avg Duration 7d Max",
        name: "shortAvgDuration7dMax",
        type: "number",
        default: 0,
        description:
          "Maximum 7-day average duration of short videos to include",
      },
      {
        displayName: "Short Avg Duration 7d Min",
        name: "shortAvgDuration7dMin",
        type: "number",
        default: 0,
        description:
          "Minimum 7-day average duration of short videos to include",
      },
      {
        displayName: "Short Video Count 1y Max",
        name: "shortVideoCount1yMax",
        type: "number",
        default: 0,
        description: "Maximum number of short videos in the last year",
      },
      {
        displayName: "Short Video Count 1y Min",
        name: "shortVideoCount1yMin",
        type: "number",
        default: 0,
        description: "Minimum number of short videos in the last year",
      },
      {
        displayName: "Short Video Count 30d Max",
        name: "shortVideoCount30dMax",
        type: "number",
        default: 0,
        description: "Maximum number of short videos in the last 30 days",
      },
      {
        displayName: "Short Video Count 30d Min",
        name: "shortVideoCount30dMin",
        type: "number",
        default: 0,
        description: "Minimum number of short videos in the last 30 days",
      },
      {
        displayName: "Short Video Count 7d Max",
        name: "shortVideoCount7dMax",
        type: "number",
        default: 0,
        description: "Maximum number of short videos in the last 7 days",
      },
      {
        displayName: "Short Video Count 7d Min",
        name: "shortVideoCount7dMin",
        type: "number",
        default: 0,
        description: "Minimum number of short videos in the last 7 days",
      },
      {
        displayName: "Short View Count 1y Max",
        name: "shortViewCount1yMax",
        type: "number",
        default: 0,
        description: "Maximum short-video view count in the last year",
      },
      {
        displayName: "Short View Count 1y Min",
        name: "shortViewCount1yMin",
        type: "number",
        default: 0,
        description: "Minimum short-video view count in the last year",
      },
      {
        displayName: "Short View Count 30d Max",
        name: "shortViewCount30dMax",
        type: "number",
        default: 0,
        description: "Maximum short-video view count in the last 30 days",
      },
      {
        displayName: "Short View Count 30d Min",
        name: "shortViewCount30dMin",
        type: "number",
        default: 0,
        description: "Minimum short-video view count in the last 30 days",
      },
      {
        displayName: "Short View Count 7d Max",
        name: "shortViewCount7dMax",
        type: "number",
        default: 0,
        description: "Maximum short-video view count in the last 7 days",
      },
      {
        displayName: "Short View Count 7d Min",
        name: "shortViewCount7dMin",
        type: "number",
        default: 0,
        description: "Minimum short-video view count in the last 7 days",
      },
      {
        displayName: "Subs Growth 1y Max",
        name: "subsGrowth1yMax",
        type: "number",
        default: 0,
        description: "Maximum 1-year subscriber growth to include",
      },
      {
        displayName: "Subs Growth 1y Min",
        name: "subsGrowth1yMin",
        type: "number",
        default: 0,
        description: "Minimum 1-year subscriber growth to include",
      },
      {
        displayName: "Subs Growth 30d Max",
        name: "subsGrowth30dMax",
        type: "number",
        default: 0,
        description: "Maximum 30-day subscriber growth to include",
      },
      {
        displayName: "Subs Growth 30d Min",
        name: "subsGrowth30dMin",
        type: "number",
        default: 0,
        description: "Minimum 30-day subscriber growth to include",
      },
      {
        displayName: "Subs Growth 7d Max",
        name: "subsGrowth7dMax",
        type: "number",
        default: 0,
        description: "Maximum 7-day subscriber growth to include",
      },
      {
        displayName: "Subs Growth 7d Min",
        name: "subsGrowth7dMin",
        type: "number",
        default: 0,
        description: "Minimum 7-day subscriber growth to include",
      },
      {
        displayName: "Views Growth 1y Max",
        name: "viewsGrowth1yMax",
        type: "number",
        default: 0,
        description: "Maximum 1-year views growth to include",
      },
      {
        displayName: "Views Growth 1y Min",
        name: "viewsGrowth1yMin",
        type: "number",
        default: 0,
        description: "Minimum 1-year views growth to include",
      },
      {
        displayName: "Views Growth 30d Max",
        name: "viewsGrowth30dMax",
        type: "number",
        default: 0,
        description: "Maximum 30-day views growth to include",
      },
      {
        displayName: "Views Growth 30d Min",
        name: "viewsGrowth30dMin",
        type: "number",
        default: 0,
        description: "Minimum 30-day views growth to include",
      },
      {
        displayName: "Views Growth 7d Max",
        name: "viewsGrowth7dMax",
        type: "number",
        default: 0,
        description: "Maximum 7-day views growth to include",
      },
      {
        displayName: "Views Growth 7d Min",
        name: "viewsGrowth7dMin",
        type: "number",
        default: 0,
        description: "Minimum 7-day views growth to include",
      },
    ],
  },

  // ----- Update Competitors -----
  {
    displayName: "YouTube Channel ID",
    name: "youtubeChannelId",
    required: true,
    type: "string",
    default: "",
    description: "YouTube channel ID to update competitors for",
    displayOptions: show("updateCompetitors"),
  },
  {
    displayName: "Follow",
    name: "follow",
    type: "string",
    default: "",
    placeholder: "a, b, c",
    description: "Competitor channel IDs to start following (comma-separated)",
    displayOptions: show("updateCompetitors"),
  },
  {
    displayName: "Unfollow",
    name: "unfollow",
    type: "string",
    default: "",
    placeholder: "a, b, c",
    description: "Competitor channel IDs to stop following (comma-separated)",
    displayOptions: show("updateCompetitors"),
  },

  {
    displayName: "Extra Arguments (JSON)",
    name: "extraArguments",
    type: "json",
    default: "{}",
    description:
      "Advanced: raw vidIQ arguments merged as a base; typed fields above take precedence",
    displayOptions: { show: { resource: ["channel"] } },
  },
];
