import { type INodeProperties } from "n8n-workflow";
import { optionsField } from "../../helpers/common";

const show = (operation: string) => ({
  show: { resource: ["trend"], operation: [operation] },
});

export const trendDescription: INodeProperties[] = [
  {
    displayName: "Operation",
    name: "operation",
    type: "options",
    noDataExpression: true,
    displayOptions: { show: { resource: ["trend"] } },
    options: [
      {
        name: "Categories",
        value: "categories",
        action: "List trend categories",
        description:
          "List all available trend category slugs with display names",
      },
      {
        name: "Trending Videos",
        value: "trendingVideos",
        action: "Find trending videos",
        description:
          "Find YouTube videos gaining views rapidly by views-per-hour velocity",
      },
      {
        name: "Video Outliers",
        value: "videoOutliers",
        action: "Find video outliers",
        description:
          "Find viral and overperforming videos exceeding their channel average",
      },
    ],
    default: "categories",
  },
  {
    displayName: "Video Format",
    name: "videoFormat",
    required: true,
    type: "options",
    options: [
      { name: "Long", value: "long" },
      { name: "Short", value: "short" },
    ],
    default: "long",
    description:
      "Video format: 'long' for regular videos, 'short' for YouTube Shorts",
    displayOptions: show("trendingVideos"),
  },
  {
    displayName: "Title Query",
    name: "titleQuery",
    type: "string",
    default: "",
    description: "Search query to filter by video title (semantic search)",
    displayOptions: show("trendingVideos"),
  },
  {
    displayName: "Subscriber Count Min",
    name: "subscriberCountMin",
    type: "number",
    default: 0,
    description: "Minimum channel subscriber count",
    displayOptions: show("trendingVideos"),
  },
  {
    displayName: "Subscriber Count Max",
    name: "subscriberCountMax",
    type: "number",
    default: 0,
    description: "Maximum channel subscriber count",
    displayOptions: show("trendingVideos"),
  },
  {
    displayName: "View Count Min",
    name: "viewCountMin",
    type: "number",
    default: 0,
    description: "Minimum video view count",
    displayOptions: show("trendingVideos"),
  },
  {
    displayName: "Min Views Per Hour",
    name: "vphMin",
    type: "number",
    default: 0,
    description: "Minimum views per hour",
    displayOptions: show("trendingVideos"),
  },
  {
    displayName: "Channel Country",
    name: "channelCountry",
    type: "string",
    default: "",
    placeholder: "US",
    description: "Filter by channel country (2-letter code, e.g. US)",
    displayOptions: show("trendingVideos"),
  },
  {
    displayName: "Video Published After",
    name: "videoPublishedAfter",
    type: "string",
    default: "",
    placeholder: "YYYY-MM-DD",
    description: "Only videos published after this ISO date (YYYY-MM-DD)",
    displayOptions: show("trendingVideos"),
  },
  {
    displayName: "Video Published Before",
    name: "videoPublishedBefore",
    type: "string",
    default: "",
    placeholder: "YYYY-MM-DD",
    description: "Only videos published before this ISO date (YYYY-MM-DD)",
    displayOptions: show("trendingVideos"),
  },
  {
    displayName: "Sort By",
    name: "sortBy",
    type: "options",
    options: [
      { name: "Engagement Rate", value: "engagementRate" },
      { name: "Relevance", value: "relevance" },
      { name: "Video Published At", value: "videoPublishedAt" },
      { name: "View Count", value: "viewCount" },
      { name: "Vph", value: "vph" },
    ],
    default: "relevance",
    description: "Sort field",
    displayOptions: show("trendingVideos"),
  },
  {
    displayName: "Limit",
    name: "limit",
    type: "number",
    typeOptions: { minValue: 1 },
    default: 50,
    description: "Max number of results to return",
    displayOptions: show("trendingVideos"),
  },
  {
    displayName: "Keyword",
    name: "keyword",
    type: "string",
    default: "",
    description:
      "Search keyword to find outlier videos by title. Optional when Channel IDs is provided.",
    displayOptions: show("videoOutliers"),
  },
  {
    displayName: "Channel IDs",
    name: "channelIds",
    type: "string",
    default: "",
    placeholder: "UCabc123, UCdef456",
    description:
      "Restrict results to one or more YouTube channels, by channel ID, handle, or URL (comma-separated)",
    displayOptions: show("videoOutliers"),
  },
  {
    displayName: "Content Type",
    name: "contentType",
    type: "options",
    options: [
      { name: "All", value: "all" },
      { name: "Long", value: "long" },
      { name: "Short", value: "short" },
    ],
    default: "all",
    description: "Filter by content type",
    displayOptions: show("videoOutliers"),
  },
  {
    displayName: "Min Outlier Score",
    name: "minOutlierScore",
    type: "number",
    default: 0,
    description: "Minimum outlier score",
    displayOptions: show("videoOutliers"),
  },
  {
    displayName: "Min Subscribers",
    name: "minSubscribers",
    type: "number",
    default: 0,
    description: "Minimum channel subscribers",
    displayOptions: show("videoOutliers"),
  },
  {
    displayName: "Max Subscribers",
    name: "maxSubscribers",
    type: "number",
    default: 0,
    description: "Maximum channel subscribers",
    displayOptions: show("videoOutliers"),
  },
  {
    displayName: "Min Views",
    name: "minViews",
    type: "number",
    default: 0,
    description: "Minimum video views",
    displayOptions: show("videoOutliers"),
  },
  {
    displayName: "Max Views",
    name: "maxViews",
    type: "number",
    default: 0,
    description: "Maximum video views",
    displayOptions: show("videoOutliers"),
  },
  {
    displayName: "Min Views Per Hour",
    name: "minVph",
    type: "number",
    default: 0,
    description: "Minimum views per hour",
    displayOptions: show("videoOutliers"),
  },
  {
    displayName: "Min Engagement Rate",
    name: "minEngagementRate",
    type: "number",
    default: 0,
    description: "Minimum engagement rate",
    displayOptions: show("videoOutliers"),
  },
  {
    displayName: "Published Within",
    name: "publishedWithin",
    type: "options",
    options: [
      { name: "All Time", value: "allTime" },
      { name: "One Year", value: "oneYear" },
      { name: "Six Months", value: "sixMonths" },
      { name: "This Month", value: "thisMonth" },
      { name: "This Week", value: "thisWeek" },
      { name: "Three Months", value: "threeMonths" },
    ],
    default: "allTime",
    description: "Filter by publish date",
    displayOptions: show("videoOutliers"),
  },
  {
    displayName: "Channel Country",
    name: "channelCountry",
    type: "string",
    default: "",
    placeholder: "US",
    description: "Filter by channel country",
    displayOptions: show("videoOutliers"),
  },
  {
    displayName: "Trend Categories",
    name: "trendCategories",
    type: "string",
    default: "",
    placeholder: "everything_wrong, i_survived",
    description:
      "Filter by trend category IDs, e.g. reaction, tier_list, mukbang (comma-separated)",
    displayOptions: show("videoOutliers"),
  },
  {
    displayName: "Sort",
    name: "sort",
    type: "options",
    options: [
      { name: "Breakout Score", value: "breakoutScore" },
      { name: "Published At", value: "publishedAt" },
      { name: "Score", value: "score" },
      { name: "View Count", value: "viewCount" },
      { name: "Vph", value: "vph" },
    ],
    default: "breakoutScore",
    description: "Sort field (defaults to score)",
    displayOptions: show("videoOutliers"),
  },
  {
    displayName: "Limit",
    name: "limit",
    type: "number",
    typeOptions: { minValue: 1 },
    default: 50,
    description: "Max number of results to return",
    displayOptions: show("videoOutliers"),
  },
  optionsField("trend"),
];
