import { type INodeProperties } from "n8n-workflow";
import { optionsField } from "../../helpers/common";

const show = (operation: string) => ({
  show: { resource: ["studio"], operation: [operation] },
});

export const studioDescription: INodeProperties[] = [
  {
    displayName: "Operation",
    name: "operation",
    type: "options",
    noDataExpression: true,
    displayOptions: { show: { resource: ["studio"] } },
    options: [
      {
        name: "Clone Voice (Upload)",
        value: "cloneVoiceUpload",
        action: "Clone a voice from an uploaded audio sample",
        description:
          "Create a cloned voice from an uploaded audio sample. Consumes vidIQ credits.",
      },
      {
        name: "Clone Voice From YouTube",
        value: "cloneVoiceFromYoutube",
        action: "Clone a voice from a you tube video",
        description:
          "Start a job that clones a voice from a YouTube video. Consumes vidIQ credits.",
      },
      {
        name: "Compose",
        value: "compose",
        action: "Compose a video from scenes",
        description:
          "Render a video from scenes, voiceover, music, overlays and captions. Consumes vidIQ credits.",
      },
      {
        name: "Find B-Roll",
        value: "findBroll",
        action: "Find b roll footage",
        description:
          "Search for stock b-roll footage matching a query. Consumes vidIQ credits.",
      },
      {
        name: "Generate Clips",
        value: "generateClips",
        action: "Generate clips from a video",
        description:
          "Start a job that cuts a long video into short clips. Consumes vidIQ credits.",
      },
      {
        name: "Generate Thumbnail",
        value: "generateThumbnail",
        action: "Generate a thumbnail",
        description:
          "Start a job that generates a thumbnail for a video. Consumes vidIQ credits.",
      },
      {
        name: "Generate Titles",
        value: "generateTitles",
        action: "Generate video titles",
        description:
          "Generate optimized title suggestions for a video. Consumes vidIQ credits.",
      },
      {
        name: "Generate Video",
        value: "generateVideo",
        action: "Generate a video",
        description:
          "Start a job that generates a video from a prompt. Consumes vidIQ credits.",
      },
      {
        name: "Generate Voiceover",
        value: "generateVoiceover",
        action: "Generate a voiceover",
        description:
          "Generate a voiceover audio track from a script. Consumes vidIQ credits.",
      },
      {
        name: "List Voices",
        value: "listVoices",
        action: "List available voices",
        description: "List the voices available for voiceover generation",
      },
      {
        name: "Refine Thumbnail",
        value: "refineThumbnail",
        action: "Refine a thumbnail",
        description:
          "Start a job that refines an existing thumbnail with instructions. Consumes vidIQ credits.",
      },
      {
        name: "Score Thumbnail",
        value: "scoreThumbnail",
        action: "Score a thumbnail",
        description:
          "Score how well a thumbnail is likely to perform. Consumes vidIQ credits.",
      },
      {
        name: "Score Title",
        value: "scoreTitle",
        action: "Score a title",
        description:
          "Score how well a title is likely to perform. Consumes vidIQ credits.",
      },
    ],
    default: "cloneVoiceUpload",
  },

  // ----- Clone Voice (Upload) -----
  {
    displayName: "Name",
    name: "name",
    required: true,
    type: "string",
    default: "",
    description: "Name for the cloned voice",
    displayOptions: show("cloneVoiceUpload"),
  },
  {
    displayName: "Audio Base64 Input Type",
    name: "audioBase64InputType",
    type: "options",
    options: [
      { name: "Binary Property", value: "binary" },
      { name: "URL", value: "url" },
    ],
    default: "url",
    description:
      "Whether audioBase64 is provided as a URL or an n8n binary property",
    displayOptions: show("cloneVoiceUpload"),
  },
  {
    displayName: "Audio Base64 (URL)",
    name: "audioBase64",
    type: "string",
    default: "",
    description: "AudioBase64 as a URL",
    displayOptions: {
      show: {
        resource: ["studio"],
        operation: ["cloneVoiceUpload"],
        audioBase64InputType: ["url"],
      },
    },
  },
  {
    displayName: "Audio Base64 Binary Property",
    name: "audioBase64BinaryProperty",
    type: "string",
    default: "data",
    description: "Name of the binary property containing audioBase64",
    displayOptions: {
      show: {
        resource: ["studio"],
        operation: ["cloneVoiceUpload"],
        audioBase64InputType: ["binary"],
      },
    },
  },
  {
    displayName: "Content Type",
    name: "contentType",
    type: "string",
    default: "",
    description: "MIME content type of the audio sample",
    displayOptions: show("cloneVoiceUpload"),
  },
  {
    displayName: "Description",
    name: "description",
    type: "string",
    default: "",
    description: "Description of the cloned voice",
    displayOptions: show("cloneVoiceUpload"),
  },

  // ----- Clone Voice From YouTube -----
  {
    displayName: "YouTube URL",
    name: "youtubeUrl",
    required: true,
    type: "string",
    default: "",
    description: "URL of the YouTube video to clone the voice from",
    displayOptions: show("cloneVoiceFromYoutube"),
  },
  {
    displayName: "Name",
    name: "name",
    required: true,
    type: "string",
    default: "",
    description: "Name for the cloned voice",
    displayOptions: show("cloneVoiceFromYoutube"),
  },

  // ----- Compose -----
  {
    displayName: "Scenes",
    name: "scenes",
    required: true,
    type: "json",
    default: "[]",
    description:
      "Array of scene objects (source, duration, type) to compose into the video",
    displayOptions: show("compose"),
  },
  {
    displayName: "Format",
    name: "format",
    required: true,
    type: "options",
    options: [
      { name: "Landscape", value: "landscape" },
      { name: "Square", value: "square" },
      { name: "Vertical", value: "vertical" },
    ],
    default: "vertical",
    description: "Output aspect ratio of the composed video",
    displayOptions: show("compose"),
  },
  {
    displayName: "Voiceover",
    name: "voiceover",
    type: "json",
    default: "{}",
    description: "Voiceover configuration object",
    displayOptions: show("compose"),
  },
  {
    displayName: "Music",
    name: "music",
    type: "json",
    default: "{}",
    description: "Background music configuration object",
    displayOptions: show("compose"),
  },
  {
    displayName: "Overlays",
    name: "overlays",
    type: "json",
    default: "[]",
    description: "Array of text overlay objects",
    displayOptions: show("compose"),
  },
  {
    displayName: "Captions",
    name: "captions",
    type: "json",
    default: "{}",
    description: "Captions configuration object",
    displayOptions: show("compose"),
  },

  // ----- Find B-Roll -----
  {
    displayName: "Query",
    name: "query",
    required: true,
    type: "string",
    default: "",
    description: "Search query describing the b-roll footage to find",
    displayOptions: show("findBroll"),
  },
  {
    displayName: "Orientation",
    name: "orientation",
    type: "options",
    options: [
      { name: "Landscape", value: "landscape" },
      { name: "Portrait", value: "portrait" },
      { name: "Square", value: "square" },
    ],
    default: "landscape",
    description: "Orientation of the b-roll footage",
    displayOptions: show("findBroll"),
  },
  {
    displayName: "Min Duration Seconds",
    name: "minDurationSeconds",
    type: "number",
    default: 0,
    description: "Minimum clip duration in seconds",
    displayOptions: show("findBroll"),
  },
  {
    displayName: "Max Duration Seconds",
    name: "maxDurationSeconds",
    type: "number",
    default: 0,
    description: "Maximum clip duration in seconds",
    displayOptions: show("findBroll"),
  },

  // ----- Generate Clips -----
  {
    displayName: "Video URL",
    name: "videoUrl",
    type: "string",
    default: "",
    description: "URL of the source video to clip",
    displayOptions: show("generateClips"),
  },
  {
    displayName: "Uploaded Video URL",
    name: "uploadedVideoUrl",
    type: "string",
    default: "",
    description: "URL of a previously uploaded source video",
    displayOptions: show("generateClips"),
  },
  {
    displayName: "Video Duration",
    name: "videoDuration",
    type: "number",
    default: 0,
    description: "Duration of the source video in seconds",
    displayOptions: show("generateClips"),
  },
  {
    displayName: "Video Filename",
    name: "videoFilename",
    type: "string",
    default: "",
    description: "Filename of the source video",
    displayOptions: show("generateClips"),
  },
  {
    displayName: "Prompt",
    name: "prompt",
    type: "string",
    default: "",
    description: "Prompt guiding which clips to generate",
    displayOptions: show("generateClips"),
  },
  {
    displayName: "Clip Duration",
    name: "clipDuration",
    type: "number",
    default: 0,
    description: "Target duration of each generated clip in seconds",
    displayOptions: show("generateClips"),
  },
  {
    displayName: "Video Language",
    name: "videoLanguage",
    type: "string",
    default: "",
    description: "Language of the source video",
    displayOptions: show("generateClips"),
  },
  {
    displayName: "Img URL",
    name: "imgUrl",
    type: "string",
    default: "",
    description: "URL of an image to use during clip generation",
    displayOptions: show("generateClips"),
  },
  {
    displayName: "Caption Style",
    name: "captionStyle",
    type: "options",
    options: [
      { name: "Chic Cut", value: "Chic Cut" },
      { name: "Classic Style", value: "Classic Style" },
      { name: "Clean Fade", value: "Clean Fade" },
      { name: "Comic Charge", value: "Comic Charge" },
      { name: "Creator Cut", value: "Creator Cut" },
      { name: "Deep Thought", value: "Deep Thought" },
      { name: "Grand Statement", value: "Grand Statement" },
      { name: "Headline Heat", value: "Headline Heat" },
      { name: "Hype Mode", value: "Hype Mode" },
      { name: "Loud & Clear", value: "Loud & Clear" },
      { name: "Midnight Read", value: "Midnight Read" },
      { name: "None", value: "none" },
      { name: "Pop Blast", value: "Pop Blast" },
      { name: "Renaissance", value: "Renaissance" },
      { name: "Snap Reaction", value: "Snap Reaction" },
      { name: "Soft Focus", value: "Soft Focus" },
      { name: "Talk Show", value: "Talk Show" },
      { name: "Urban Voice", value: "Urban Voice" },
      { name: "Vlog Pop", value: "Vlog Pop" },
    ],
    default: "Classic Style",
    description: "Caption style applied to the generated clips",
    displayOptions: show("generateClips"),
  },
  {
    displayName: "Processing Start Seconds",
    name: "processingStartSeconds",
    type: "number",
    default: 0,
    description: "Start offset in seconds for the portion of video to process",
    displayOptions: show("generateClips"),
  },
  {
    displayName: "Processing End Seconds",
    name: "processingEndSeconds",
    type: "number",
    default: 0,
    description: "End offset in seconds for the portion of video to process",
    displayOptions: show("generateClips"),
  },

  // ----- Generate Thumbnail -----
  {
    displayName: "Video ID",
    name: "videoId",
    type: "string",
    default: "",
    description: "ID of the video to generate a thumbnail for",
    displayOptions: show("generateThumbnail"),
  },
  {
    displayName: "Title",
    name: "title",
    type: "string",
    default: "",
    description: "Title of the video",
    displayOptions: show("generateThumbnail"),
  },
  {
    displayName: "Description",
    name: "description",
    type: "string",
    default: "",
    description: "Description of the video",
    displayOptions: show("generateThumbnail"),
  },
  {
    displayName: "Transcript",
    name: "transcript",
    type: "string",
    default: "",
    description: "Transcript of the video",
    displayOptions: show("generateThumbnail"),
  },
  {
    displayName: "User Query",
    name: "userQuery",
    type: "string",
    default: "",
    description: "Additional user guidance for the thumbnail",
    displayOptions: show("generateThumbnail"),
  },
  {
    displayName: "Current Thumbnail Input Type",
    name: "currentThumbnailInputType",
    type: "options",
    options: [
      { name: "Binary Property", value: "binary" },
      { name: "URL", value: "url" },
    ],
    default: "url",
    description:
      "Whether currentThumbnail is provided as a URL or an n8n binary property",
    displayOptions: show("generateThumbnail"),
  },
  {
    displayName: "Current Thumbnail (URL)",
    name: "currentThumbnail",
    type: "string",
    default: "",
    description: "CurrentThumbnail as a URL",
    displayOptions: {
      show: {
        resource: ["studio"],
        operation: ["generateThumbnail"],
        currentThumbnailInputType: ["url"],
      },
    },
  },
  {
    displayName: "Current Thumbnail Binary Property",
    name: "currentThumbnailBinaryProperty",
    type: "string",
    default: "data",
    description: "Name of the binary property containing currentThumbnail",
    displayOptions: {
      show: {
        resource: ["studio"],
        operation: ["generateThumbnail"],
        currentThumbnailInputType: ["binary"],
      },
    },
  },
  {
    displayName: "Subject Image Input Type",
    name: "subjectImageInputType",
    type: "options",
    options: [
      { name: "Binary Property", value: "binary" },
      { name: "URL", value: "url" },
    ],
    default: "url",
    description:
      "Whether subjectImage is provided as a URL or an n8n binary property",
    displayOptions: show("generateThumbnail"),
  },
  {
    displayName: "Subject Image (URL)",
    name: "subjectImage",
    type: "string",
    default: "",
    description: "SubjectImage as a URL",
    displayOptions: {
      show: {
        resource: ["studio"],
        operation: ["generateThumbnail"],
        subjectImageInputType: ["url"],
      },
    },
  },
  {
    displayName: "Subject Image Binary Property",
    name: "subjectImageBinaryProperty",
    type: "string",
    default: "data",
    description: "Name of the binary property containing subjectImage",
    displayOptions: {
      show: {
        resource: ["studio"],
        operation: ["generateThumbnail"],
        subjectImageInputType: ["binary"],
      },
    },
  },
  {
    displayName: "Reference Images",
    name: "referenceImages",
    type: "json",
    default: "[]",
    description: "Array of reference image URLs",
    displayOptions: show("generateThumbnail"),
  },
  {
    displayName: "Feedback",
    name: "feedback",
    type: "json",
    default: "{}",
    description: "Feedback object to guide thumbnail generation",
    displayOptions: show("generateThumbnail"),
  },

  // ----- Generate Titles -----
  {
    displayName: "Video ID",
    name: "videoId",
    type: "string",
    default: "",
    description: "ID of the video to generate titles for",
    displayOptions: show("generateTitles"),
  },
  {
    displayName: "Title",
    name: "title",
    type: "string",
    default: "",
    description: "Current title of the video",
    displayOptions: show("generateTitles"),
  },
  {
    displayName: "Description",
    name: "description",
    type: "string",
    default: "",
    description: "Description of the video",
    displayOptions: show("generateTitles"),
  },
  {
    displayName: "Num Titles",
    name: "numTitles",
    type: "number",
    default: 0,
    description: "Number of title suggestions to generate",
    displayOptions: show("generateTitles"),
  },
  {
    displayName: "Type",
    name: "type",
    type: "options",
    options: [
      { name: "Long", value: "long" },
      { name: "Short", value: "short" },
    ],
    default: "long",
    description: "Whether to generate long-form or short-form titles",
    displayOptions: show("generateTitles"),
  },
  {
    displayName: "Language",
    name: "language",
    type: "string",
    default: "",
    description: "Language of the generated titles",
    displayOptions: show("generateTitles"),
  },
  {
    displayName: "Region Code",
    name: "regionCode",
    type: "string",
    default: "",
    description: "Region code to localize the generated titles",
    displayOptions: show("generateTitles"),
  },
  {
    displayName: "Score Threshold",
    name: "scoreThreshold",
    type: "number",
    default: 0,
    description: "Minimum score a generated title must meet",
    displayOptions: show("generateTitles"),
  },
  {
    displayName: "Previous Titles",
    name: "previousTitles",
    type: "string",
    default: "",
    placeholder: "My old title, Another title",
    description: "Previously used titles to avoid repeating (comma-separated)",
    displayOptions: show("generateTitles"),
  },
  {
    displayName: "Competitor Titles",
    name: "competitorTitles",
    type: "json",
    default: "[]",
    description: "Array of competitor titles for context",
    displayOptions: show("generateTitles"),
  },
  {
    displayName: "Analysis Summary",
    name: "analysisSummary",
    type: "string",
    default: "",
    description: "Summary of prior analysis to inform title generation",
    displayOptions: show("generateTitles"),
  },

  // ----- Generate Video -----
  {
    displayName: "Prompt",
    name: "prompt",
    required: true,
    type: "string",
    default: "",
    description: "Text prompt describing the video to generate",
    displayOptions: show("generateVideo"),
  },
  {
    displayName: "Model",
    name: "model",
    type: "options",
    options: [
      { name: "Kling 3", value: "kling-3" },
      { name: "Kling 3 Pro", value: "kling-3-pro" },
      { name: "Seedance 1 5 Pro", value: "seedance-1-5-pro" },
      { name: "Seedance 2", value: "seedance-2" },
      { name: "Seedance 2 Fast", value: "seedance-2-fast" },
      { name: "Sora 2", value: "sora-2" },
      { name: "Sora 2 Pro", value: "sora-2-pro" },
      { name: "Veo 3.1", value: "veo-3.1" },
      { name: "Veo 3.1 Fast", value: "veo-3.1-fast" },
      { name: "Veo 3.1 Lite", value: "veo-3.1-lite" },
    ],
    default: "sora-2",
    description: "Generative model to use for video generation",
    displayOptions: show("generateVideo"),
  },
  {
    displayName: "Resolution",
    name: "resolution",
    required: true,
    type: "options",
    options: [
      { name: "1024p", value: "1024p" },
      { name: "1080p", value: "1080p" },
      { name: "720p", value: "720p" },
    ],
    default: "720p",
    description: "Output resolution of the generated video",
    displayOptions: show("generateVideo"),
  },
  {
    displayName: "Duration",
    name: "duration",
    type: "number",
    default: 8,
    required: true,
    typeOptions: { minValue: 1 },
    description:
      "Duration of the generated video in seconds (required; valid range depends on the model)",
    displayOptions: show("generateVideo"),
  },
  {
    displayName: "Aspect Ratio",
    name: "aspectRatio",
    type: "options",
    options: [
      { name: "16:9", value: "16:9" },
      { name: "9:16", value: "9:16" },
    ],
    default: "9:16",
    description: "Aspect ratio of the generated video",
    displayOptions: show("generateVideo"),
  },
  {
    displayName: "Remix Video ID",
    name: "remixVideoId",
    type: "string",
    default: "",
    description: "ID of an existing video to remix",
    displayOptions: show("generateVideo"),
  },
  {
    displayName: "Remix Project ID",
    name: "remixProjectId",
    type: "string",
    default: "",
    description: "ID of an existing project to remix",
    displayOptions: show("generateVideo"),
  },
  {
    displayName: "Start Frame B64 Input Type",
    name: "startFrameB64InputType",
    type: "options",
    options: [
      { name: "Binary Property", value: "binary" },
      { name: "URL", value: "url" },
    ],
    default: "url",
    description:
      "Whether startFrameB64 is provided as a URL or an n8n binary property",
    displayOptions: show("generateVideo"),
  },
  {
    displayName: "Start Frame B64 (URL)",
    name: "startFrameB64",
    type: "string",
    default: "",
    description: "StartFrameB64 as a URL",
    displayOptions: {
      show: {
        resource: ["studio"],
        operation: ["generateVideo"],
        startFrameB64InputType: ["url"],
      },
    },
  },
  {
    displayName: "Start Frame B64 Binary Property",
    name: "startFrameB64BinaryProperty",
    type: "string",
    default: "data",
    description: "Name of the binary property containing startFrameB64",
    displayOptions: {
      show: {
        resource: ["studio"],
        operation: ["generateVideo"],
        startFrameB64InputType: ["binary"],
      },
    },
  },
  {
    displayName: "End Frame B64 Input Type",
    name: "endFrameB64InputType",
    type: "options",
    options: [
      { name: "Binary Property", value: "binary" },
      { name: "URL", value: "url" },
    ],
    default: "url",
    description:
      "Whether endFrameB64 is provided as a URL or an n8n binary property",
    displayOptions: show("generateVideo"),
  },
  {
    displayName: "End Frame B64 (URL)",
    name: "endFrameB64",
    type: "string",
    default: "",
    description: "EndFrameB64 as a URL",
    displayOptions: {
      show: {
        resource: ["studio"],
        operation: ["generateVideo"],
        endFrameB64InputType: ["url"],
      },
    },
  },
  {
    displayName: "End Frame B64 Binary Property",
    name: "endFrameB64BinaryProperty",
    type: "string",
    default: "data",
    description: "Name of the binary property containing endFrameB64",
    displayOptions: {
      show: {
        resource: ["studio"],
        operation: ["generateVideo"],
        endFrameB64InputType: ["binary"],
      },
    },
  },

  // ----- Generate Voiceover -----
  {
    displayName: "Text to Convert to Speech",
    name: "script",
    required: true,
    type: "string",
    default: "",
    description: "The text to synthesize into speech (max 5000 characters)",
    displayOptions: show("generateVoiceover"),
  },
  {
    displayName: "Voice ID",
    name: "voiceId",
    required: true,
    type: "string",
    default: "",
    description: "ID of the voice to use for the voiceover",
    displayOptions: show("generateVoiceover"),
  },
  {
    displayName: "Output",
    name: "output",
    type: "options",
    options: [
      { name: "URL and Audio", value: "url_and_audio" },
      { name: "URL Only", value: "url_only" },
    ],
    default: "url_only",
    description: "Whether to return only a URL or the URL and audio data",
    displayOptions: show("generateVoiceover"),
  },

  // ----- Refine Thumbnail -----
  {
    displayName: "Source Thumbnail Input Type",
    name: "sourceThumbnailInputType",
    type: "options",
    options: [
      { name: "Binary Property", value: "binary" },
      { name: "URL", value: "url" },
    ],
    default: "url",
    description:
      "Whether sourceThumbnail is provided as a URL or an n8n binary property",
    displayOptions: show("refineThumbnail"),
  },
  {
    displayName: "Source Thumbnail (URL)",
    name: "sourceThumbnail",
    type: "string",
    default: "",
    description: "SourceThumbnail as a URL",
    displayOptions: {
      show: {
        resource: ["studio"],
        operation: ["refineThumbnail"],
        sourceThumbnailInputType: ["url"],
      },
    },
  },
  {
    displayName: "Source Thumbnail Binary Property",
    name: "sourceThumbnailBinaryProperty",
    type: "string",
    default: "data",
    description: "Name of the binary property containing sourceThumbnail",
    displayOptions: {
      show: {
        resource: ["studio"],
        operation: ["refineThumbnail"],
        sourceThumbnailInputType: ["binary"],
      },
    },
  },
  {
    displayName: "Instructions",
    name: "instructions",
    required: true,
    type: "string",
    default: "",
    description: "Instructions describing how to refine the thumbnail",
    displayOptions: show("refineThumbnail"),
  },
  {
    displayName: "Original Concept",
    name: "originalConcept",
    type: "string",
    default: "",
    description: "Original concept the thumbnail was based on",
    displayOptions: show("refineThumbnail"),
  },
  {
    displayName: "Video ID",
    name: "videoId",
    type: "string",
    default: "",
    description: "ID of the video the thumbnail belongs to",
    displayOptions: show("refineThumbnail"),
  },
  {
    displayName: "Subject Image Input Type",
    name: "subjectImageInputType",
    type: "options",
    options: [
      { name: "Binary Property", value: "binary" },
      { name: "URL", value: "url" },
    ],
    default: "url",
    description:
      "Whether subjectImage is provided as a URL or an n8n binary property",
    displayOptions: show("refineThumbnail"),
  },
  {
    displayName: "Subject Image (URL)",
    name: "subjectImage",
    type: "string",
    default: "",
    description: "SubjectImage as a URL",
    displayOptions: {
      show: {
        resource: ["studio"],
        operation: ["refineThumbnail"],
        subjectImageInputType: ["url"],
      },
    },
  },
  {
    displayName: "Subject Image Binary Property",
    name: "subjectImageBinaryProperty",
    type: "string",
    default: "data",
    description: "Name of the binary property containing subjectImage",
    displayOptions: {
      show: {
        resource: ["studio"],
        operation: ["refineThumbnail"],
        subjectImageInputType: ["binary"],
      },
    },
  },
  {
    displayName: "Reference Images",
    name: "referenceImages",
    type: "json",
    default: "[]",
    description: "Array of reference image URLs",
    displayOptions: show("refineThumbnail"),
  },
  {
    displayName: "Mask Input Type",
    name: "maskInputType",
    type: "options",
    options: [
      { name: "Binary Property", value: "binary" },
      { name: "URL", value: "url" },
    ],
    default: "url",
    description: "Whether mask is provided as a URL or an n8n binary property",
    displayOptions: show("refineThumbnail"),
  },
  {
    displayName: "Mask (URL)",
    name: "mask",
    type: "string",
    default: "",
    description: "Mask as a URL",
    displayOptions: {
      show: {
        resource: ["studio"],
        operation: ["refineThumbnail"],
        maskInputType: ["url"],
      },
    },
  },
  {
    displayName: "Mask Binary Property",
    name: "maskBinaryProperty",
    type: "string",
    default: "data",
    description: "Name of the binary property containing mask",
    displayOptions: {
      show: {
        resource: ["studio"],
        operation: ["refineThumbnail"],
        maskInputType: ["binary"],
      },
    },
  },

  // ----- Score Thumbnail -----
  {
    displayName: "Video ID",
    name: "videoId",
    required: true,
    type: "string",
    default: "",
    description: "ID of the video the thumbnail belongs to",
    displayOptions: show("scoreThumbnail"),
  },
  {
    displayName: "Title",
    name: "title",
    required: true,
    type: "string",
    default: "",
    description: "Title of the video",
    displayOptions: show("scoreThumbnail"),
  },
  {
    displayName: "Image Input Type",
    name: "imageInputType",
    type: "options",
    options: [
      { name: "Binary Property", value: "binary" },
      { name: "URL", value: "url" },
    ],
    default: "url",
    description: "Whether image is provided as a URL or an n8n binary property",
    displayOptions: show("scoreThumbnail"),
  },
  {
    displayName: "Image (URL)",
    name: "image",
    type: "string",
    default: "",
    description: "Image as a URL",
    displayOptions: {
      show: {
        resource: ["studio"],
        operation: ["scoreThumbnail"],
        imageInputType: ["url"],
      },
    },
  },
  {
    displayName: "Image Binary Property",
    name: "imageBinaryProperty",
    type: "string",
    default: "data",
    description: "Name of the binary property containing image",
    displayOptions: {
      show: {
        resource: ["studio"],
        operation: ["scoreThumbnail"],
        imageInputType: ["binary"],
      },
    },
  },

  // ----- Score Title -----
  {
    displayName: "Title",
    name: "title",
    required: true,
    type: "string",
    default: "",
    description: "Title to score",
    displayOptions: show("scoreTitle"),
  },
  {
    displayName: "Type",
    name: "type",
    required: true,
    type: "options",
    options: [
      { name: "Long", value: "long" },
      { name: "Short", value: "short" },
    ],
    default: "long",
    description: "Whether to score the title as long-form or short-form",
    displayOptions: show("scoreTitle"),
  },
  {
    displayName: "Video ID",
    name: "videoId",
    type: "string",
    default: "",
    description: "ID of the video the title belongs to",
    displayOptions: show("scoreTitle"),
  },
  {
    displayName: "Channel ID",
    name: "channelId",
    type: "string",
    default: "",
    description: "ID of the channel the title belongs to",
    displayOptions: show("scoreTitle"),
  },

  optionsField("studio"),
];
